### ISSUE TITLE
Review of meetnetten-butterflies-egg-occurrences

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#1]
## Event

- [x] ~`coordinateUncertaintyInMeters`~: `3536` **is the data generalized to UTM**? If so, we should have:
  - `verbatimCoordinates`: `31UFS18B` and alike
  - `verbatimCoordinateSystem`: `UTM 5km`
  -  `verbatimSRS`: `WGS84`
  - `georeferenceRemarks`: `coordinates are centroid of used grid square`
  - `dataGeneralizations: `coordinates are generalized to a 5x5km UTM grid`
- [x] `informationWithheld`: `High resolution data available on request` => it might be better to write something in `dataGeneralizations` instead, see remark above
- [x] `parentEventID`: `INBO:MEETNET:VISITID :000487`: drop extra space
- [x] ~`parentEventID`: can we have those even if they are not present in the dataset?~
- [x] `samplingProtocol`: `butterflies egg counts` -> `egg count`
- [x] `eventDate`: why do times have decimals `2016-08-16 10:00:00.0`?
- [x] ~`eventDate`: what is the time zone of the dates?~
- [x] `locationID`: why the long padding with 0: `INBO:MEETNET:LOCATION:0000017359`?
- [x] `georeferenceRemarks`: `original geomerty is a: POLYGON` **typo** and I'm not sure I understand this, see first remark

## Occurrence

- [x] `occurrenceRemarks`: `data collected in the Gentiaanblauwtje monitoring scheme` = very similar to `eventRemarks`: `data collected in the Gentiaanblauwtje project`. I would only keep `eventRemarks`
- [x] `recordedBy`: `Meetnetten`. This is a bit odd. If you want to use something generic, then I would use `https://meetnetten.be`
- [x] `samplingProtocol`: `Vlinders - Eitellingen` this is going to conflict with the `samplingProtocol` from `Events`. Drop field.
- [x] `class`:  this field is empty (expecting `Insecta`). Is `class` a reserved name?
- [x] `order`: add this field with `Lepidoptera`?
- [x] ~`scientificNameAuthorship`: maybe add this field?~
- [x] `taxonRank`: add this field with `species`

**Comment by DimEvil** [comment]
## Event

- [ ] `coordinateUncertaintyInMeters`: `3536` **is the data generalized to UTM**? If so, we should have:
  - `verbatimCoordinates`: `31UFS18B` and alike
  - `verbatimCoordinateSystem`: `UTM 5km`
  -  `verbatimSRS`: `WGS84`
  - `georeferenceRemarks`: `coordinates are centroid of used grid square`
  - `dataGeneralizations: `coordinates are generalized to a 5x5km UTM grid`

Original data is decimal lat-long point coordinates, they are blurred and projected as the centroid of the UTM square. , blur is based on the project and the place. (i.e. Aardbeivlinder = UTM 5km and location is in military area UTM = 10 km). 


- [ ] `informationWithheld`: `High resolution data available on request` => it might be better to write something in `dataGeneralizations` instead, see remark above

No, this is not a data generalization, this is information withHeld :)

- [X] `parentEventID`: `INBO:MEETNET:VISITID :000487`: drop extra space

- [ ] `parentEventID`: can we have those even if they are not present in the dataset?

Don't understand

- [ ] `samplingProtocol`: `butterflies egg counts` -> `egg count`

The protocol is butterfly egg count

- [X] `eventDate`: why do times have decimals `2016-08-16 10:00:00.0`?

Changed to YYYY-MM-DD

- [ ] `eventDate`: what is the time zone of the dates?

What is the time zone of the dates?

- [X] `locationID`: why the long padding with 0: `INBO:MEETNET:LOCATION:0000017359`?

fixed, removed long padding

- [ ] `georeferenceRemarks`: `original geomerty is a: POLYGON` **typo** and I'm not sure I understand this, see first remark

There is a very complicated way of lowering the resolution, partly based on the designed sampling locations. those can be polygons, transects, multiple transects....

**Comment by peterdesmet** [comment]
Regarding the generalization, I would suggest:

- `dataGeneralizations`: `coordinates are generalized from a POLYGON to a 5x5km UTM grid`
- `georeferenceRemarks`: `coordinates are centroid of used grid square`

If need be, you could add:

- `informationWithheld`: `see metadata`

**Comment by peterdesmet** [comment]
@DimEvil, some minor things left. Best not to republish before I tackled the metadata

- [x] `informationWithheld`: **point coordinates** available on request
- [x] `dataGeneralizations`: **coordinates** are generalized from **a** POLYGON to a UTM 5Km grid
- [x] `samplingProtocol`:  butter**fly** egg counts (there are multiple counts right?)
- [x] `georeferenceRemarks`: coordinates are centroid of used grid square

**Comment by DimEvil** [comment]
I don't really see the difference for sampling protocol and georeferenceREmarks

WHEN 'Vlinders - Eitellingen' THEN 'butterfly egg count'  
, [georeferenceRemarks] = 'coordinates are centroid of used grid square'
