### ISSUE TITLE
Review of 25 meetnetten-amfibieen-larven-occurrences

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#10]
IPT dataset: meetnetten-amfibieen-larven-occurrences

# event

- [x] datasetName: Update title (see #9)
- [x] samplingProtocol: use "larvae" (see #9)

# occ

- [x] lifeStage: lowercase `larva`. Are there also `metamorph` indicated as such? If not, do we really need it in the dataset title?

# mof

- [x] `ph value` → `ph`
- [x] `present fish` → `fish present` (first one implies a list of fish, second works better for boolean)
- [x] `surface pond` → `pond surface`
- [x] `waterquality` → `water quality`
- [x] `maximum depth`: would change one value so it is a range: <0.5, 0.5-1, **1-1.5** (rather than `>1`), >1.5
- [x] `ph value`: has `unknown`, but I would use an empty value instead, as it is a number field (cf. number of sweeps)?
- [x] `waterquality`: map `slecht (verwaarloosde poel me...`) to `bad`

**Comment by DimEvil** [comment]
There are 2 similar protocols (25 & 32) they can be lumped.
WHEN 'Amfibieën - Larven' THEN 'amphibia larvae count'
WHEN 'Amfibieën - Larven en metamorfen' THEN 'amphibia larvae and metamorphs count'

**Comment by peterdesmet** [comment]
Great! The remaining issues in v1.1:

- [x] EVENT `samplingProtocol` has the unmapped value `Amfibieën - Larven en metamorfen` rather than `amphibia larvae and metamorphs count`
- [x] OCC many occurrences (e.g. `INBO:MEETNET:EVENT:200660` don't have an associated event
- [x] OCC lifestage: `Larva` -> `larva` en `metamorf` -> `metamorph`
- [x] ~OCC scientificName: `Pelobates lessonae` occurs as well as `Pelophylax lessonae`. The first is not a known scientific name.~
- [x] OCC taxonRank: `Pelophylax esculenta synklepton` should be `speciesAggregate `
- [x] OCC taxonRank: `Lissotriton spec.` should be `genus`
- [x] MEAS changes not implemented yet (maybe not yet included in v1.1)
- [ ] MEAS measurementType: translate `zoekinspanning` to `sampling effort` and translate values. Maybe it's even better this goes into the event core `samplingEffort`

**Comment by peterdesmet** [comment]
v1.2:

- [x] samplingProtocol: suggest "amphibia larvae and metamorph**s** count"
- [x] measurementType `type effort`, suggest to change to `sampling effort type`
- [ ] many measurementValues are unmapped (those that are ok have no mapping suggestion):

measurementType | measurementValue | mapping suggestion
--- | --- | ---
fish present | FALSE | 
fish present | ja | TRUE
fish present | nee | FALSE
fish present | niet bekeken/niet van toepassing | (NA)
fish present | TRUE | 
fish present | U | (NA)
fish present | (NA) | 
maximum depth | >1.5 | 
maximum depth | 0-0.5 | 
maximum depth | 0.5-1 | 
maximum depth | 1-1.5 | 
maximum depth | niet bekeken/niet van toepassing | (NA)
maximum depth | unknown | (NA)
number of sweeps | -4 | a negative value?
number of sweeps | 0 | 
number of sweeps | 10 | 
number of sweeps | 12 | 
number of sweeps | 13 | 
number of sweeps | 15 | 
number of sweeps | 18 | 
number of sweeps | 2 | 
number of sweeps | 20 | 
number of sweeps | 25 | 
number of sweeps | 3 | 
number of sweeps | 30 | 
number of sweeps | 4 | 
number of sweeps | 40 | 
number of sweeps | 5 | 
number of sweeps | 6 | 
number of sweeps | 7 | 
number of sweeps | 8 | 
number of sweeps | 9 | 
number of sweeps | (NA) | 
permanent water column | FALSE | 
permanent water column | ja | TRUE
permanent water column | nee | FALSE
permanent water column | niet bekeken/niet van toepassing | (NA)
permanent water column | TRUE | 
permanent water column | (NA) | 
pH | 6 | 
pH | 7 | 
pH | 8 | 
pH | (NA) | 
pond surface | <10 | 
pond surface | >400 | 
pond surface | 10-100 | 
pond surface | 101-250 | 
pond surface | 251-400 | 
pond surface | niet bekeken/niet van toepassing | (NA)
pond surface | (NA) | 
shading | <30% | 
shading | >60% | 
shading | 30-60% | 
shading | niet bekeken/niet van toepassing | (NA)
shading | no shade | no shading
shading | no shading | 
shading | unknown | (empty)
type effort | sweep for larvae only | 
type effort | sweep for larvae, metamorphs counted on land | 
type effort | (NA) | 
water quality | 3 | ???
water quality | average | 
water quality | bad | 
water quality | good | 
water quality | niet bekeken/niet van toepassing | (NA)
water quality | plas verdwenen of volledig verland | pond has disappeared
water quality | unknown | (NA)

**Comment by DimEvil** [comment]
whip this @peterdesmet

**Comment by peterdesmet** [comment]
Whipped real good. 💪
