### ISSUE TITLE
Review of 5+33 meetnetten-amfibieen-roepkoren-occurrences

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#11]
Reviewed v1.0

## event

- [x] datasetName: still old name
- [x] samplingProtocol: contains `Rugstreeppad - Roepkoren`

## occ

- [x] taxonRank: use `speciesAggregate` for `Pelophylax esculenta synklepton`

**Comment by peterdesmet** [comment]
- [x] samplingProtocol: now has `Natterjack toad choir count`, would use lowercase `natterjack toad choir count`, cf. `amphibia choir count`

**Comment by DimEvil** [comment]
whip this @peterdesmet

**Comment by peterdesmet** [comment]
Whip cracked, dataset didn't budge. 🎉
