### ISSUE TITLE
Coordinates not in centre of UTM

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#12]
I noticed coordinates for `25+32 meetnetten-amfibieen-larven-metamorfen-occurrences` being far West (2.50 rather than the maximum 2.53). Plotting it in QGIS, I don't understand how the coordinates are obtained. They don't seem to be the centroid of the UTM10 grid:

<img width="351" alt="Screenshot 2020-07-31 at 15 26 39" src="https://user-images.githubusercontent.com/600993/89039657-bec36480-d342-11ea-8f2f-1727732531c7.png">

**Comment by DimEvil** [comment]
![image](https://user-images.githubusercontent.com/3965195/90138969-00f39980-dd78-11ea-8d95-f4881493f3ab.png)

Can you check again, this looks like centroid UTM10

![image](https://user-images.githubusercontent.com/3965195/90139115-35675580-dd78-11ea-841a-da2608b29d42.png) (UTM 1km)

![image](https://user-images.githubusercontent.com/3965195/90139196-5334ba80-dd78-11ea-917b-c1039ef86f32.png)
 (UTM 5km)

**Comment by peterdesmet** [comment]
Hmm, that looks indeed correct. Sees I was using the EEA 10km reference grid, which is apparently not the same
