### ISSUE TITLE
Review of 34 meetnetten-rugstreeppad-zichtwaarneming-occurrences

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#13]
Review of v1.0

# event

- [x] datasetName: should be `Meetnetten.be - Sightings for Natterjack toad in Flanders, Belgium` (currently Dutch)

# occ

- [x] lifestage: maybe better to use singular `larva` instead of plural `larvae` (cf. egg, juvenile, adult)

**Comment by DimEvil** [comment]
Whip this

**Comment by peterdesmet** [comment]
Whip succeeded! 🥳
