### ISSUE TITLE
Review of 4 meetnetten-vuursalamander-transect-occurrences

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#14]
# event

- [x] datasetName: should be `Meetnetten.be - Transects for fire salamanders in Flanders, Belgium` (currently lowercase in singular salamander)

# occ

- [x] lifeStage: all values are `post-metamorf` (what is the English translation for this? `adult`?) -> `post-metamorph`
- [x] sex: all values are `unknown`: if it is never recorded, than we can drop this field (is already the case in other datasets) **nofix**

**Comment by DimEvil** [comment]
I would leave all values in 'sex' as this is a data in the original database

**Comment by DimEvil** [comment]
@peterdesmet Whip it

**Comment by peterdesmet** [comment]
Whip approved! 👏
