### ISSUE TITLE
Remove/update fields in SQL queries

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#15]
@DimEvil about a month ago I checked `behavior` in all SQL queries from the IPT, and recorded what fields should be renamed/completed or could be removed. Can you have a look at this? Note: since I checked this a while ago, not all might still be the case.

meetnetten-amfibieen-larven-metamorfen-occurrences

- [x] event:datasetID: to complete
- [x] event:parentLocality0: remove
- [x] event:recordedBy: remove
- [x] mof:parentEventID: remove

meetnetten-libellen-populatietelling-occurrences

- [x] event:datasetID: to be completed
- [x] event:parentLocality0: remove
- [x] event:recordedBy: remove
- [x] occ:behaviour: rename

meetnetten-amfibieen-fuiken-occurrences

- [x] event:datasetID: to complete
- [x] event:parentLocality0: remove
- [x] event:recordedBy: remove

meetnetten-butterflies-egg-occurrences

- [x] event:datasetID: ok
- [x] event:parentLocality0: remove
- [x] event:locality1: remove
- [x] event:recordedBy: remove

meetnetten-butterflies-area-occurrences

- [x] event:datasetID: ok
- [x] event:parentLocality0: remove
- [x] event:locality: remove
- [x] event:recordedBy: remove
- [x] mof:parentEventID: remove
- [x] mof:eventDate: remove

meetnetten-butterflies-occurrences

- [x] event:datasetID: ok
- [x] event:parentLocality0: remove
- [ ] event:locality: remove
- [x] event:recordedBy: remove
- [x] mof:parentEventID: remove
- [x] mof:eventDate: remove
- [ ] occ:protocol: remove

meetnetten-libellen-larvenhuidjes-occurrences

- [x] event:datasetID: to complete
- [x] event:parentLocality0: remove
- [x] event:recordedBy: remove
- [x] mof:parentEventID: remove
- [x] mof:eventDate: remove
- [x] occ:behaviour: rename

meetnetten-libellen-transect-occurrences

- [x] event:datasetID: ok
- [x] event:parentLocality0: remove
- [x] event:recordedBy: remove
- [x] mof:parentEventID: remove
- [x] occ:behaviour: rename

meetnetten-vuursalamander-transect-occurrences

- [x] event:datasetID: to complete
- [x] event:parentLocality0: remove
- [x] event:recordedBy: remove
- [x] occ:behaviour: rename

meetnetten-amphibia-roepkoren-occurrences

- [x] event:datasetID: to complete
- [x] event:parentLocality0: remove
- [x] event:recordedBy: remove
- [x] occ:behaviour: rename

meetnetten-rugstreeppad-zichtwaarneming-occurrences

- [x] event:datasetID: to complete
- [x] event:parentLocality0: remove
- [x] event:recordedBy: remove
- [ ] occ:behaviour: rename

**Comment by DimEvil** [comment]
@peterdesmet   Done!
