### ISSUE TITLE
Review of ABV post 2016

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#18]
## Event

- [x] datasetName: "Meetnetten - Algemene broedvogelmonitoring, Belgium, post 2016"
  - 1. I don't think the title should be in Dutch
  - 2. We should somehow link it with the old dataset: `ABV - Common breeding birds in Flanders, Belgium`
  - 3. The scope is probably Flanders, not Belgium?
  - 4. The post part should be in parenthesis cf. other datasets.
  - So maybe: `ABV - Common breeding birds in Flanders, Belgium (post 2016)`? Especially since you also used `ABV` as collection code rather than `meetnetten `
- [x] informationWithheld is typically "original locations available upon request", why not here?
**information is not withheld here, similar as original ABV**
- [x] dataGeneralizations is typically "coordinates are generalized from a ...", why not here?
**information is not withheld here, similar as original ABV**
- [x] eventID: is of format `INBO:MEETNET:AB:EVENT:005450` rather than `INBO:MEETNET:EVENT:005450`. I would keep it consistent with other datasets.
- [x] samplingEffort: typo, correct to `6 times 5 minutes count per UTM 1km`
- [x] eventDate is currently of format `2017-03-01 07:30:00.0`. Since it is only precise to the minute, it should have format `2017-03-01T07:30` (notice the T as well) **yyyy-mm-dd now**
- [x] locationID is of format `INBO:MEETNET:LOCATION:0000006265` rather than `INBO:MEETNET:LOCATION:006265` (6 digits). I would keep it consistent with other datasets.
- [x] What is the difference between `locality` (Dijleland) and `verbatimLocality` (ABV_FS2132)? It seems the verbatim one is the precise one that is always populated), while `locality` does not provide much. I would keep the values of verbatimLocality, but move it to `locality`.
**verbatimLocality is the ABV_CODE_UTM_CODE , locality is the region name It's given when provided in the database.  As abv is in the database these are not verbatimCoordinates**

## Occurrence

- [x] taxonRank: missing field, good to add it
- [x] class: has `AVES` rather than `Aves`
- [x] eventID: same format issue
- [x] occurrenceID has format `INBO:MEETNETTEN:AB:OCC:0013078` rather than `INBO:MEETNETTEN:OCC:0013078`. I would keep it consistent with other datasets.
- [x] recordedBy is `meetnetten` while other datasets use `https://meetnetten.be`
- [x] taxonID: is this a new field? If these are EURING codes, I would express them as `euring:id`, cf. watervogels + broedvogelatlas: https://github.com/inbo/data-publication/search?q=euring

**Comment by DimEvil** [comment]
@peterdesmet  skip locality? and keep verbatimLocality? (would not use verbatimCoordinates)

**Comment by DimEvil** [comment]
I dropped locality, I make a new version

**Comment by peterdesmet** [comment]
- [x] taxonRank: `Carduelis flammea cabaret`, `Motacilla flava flavissima` and `Motacilla alba yarelli` are subspecies
- [x] samplingEffort: `6 times 5 minutes count per UMT 1km` still contains a typo
- [x] occurrenceID: contains `MEETNETTEN`, while we have always used `MEETNET`: `INBO:MEETNET:OCC:\d{6,7}`
- [x] eventDate: would try to keep hour information, can be useful
