### ISSUE TITLE
Review of meetnetten-butterflies-occurrences

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#2]
## Event core

- [x] datasetID: use full URL `https://doi.org/10.15468/kfhvy4`
- [x] datasetName: `Meetnetten.be - Transects for butterflies in Flanders, Belgium`: currently missing the `-`
- [ ] ~datasetName: additional question. Should we use "Transect **counts** for butterflies"?~ *No*

## occurrence core

- [x] `occurrenceStatus`: add this field
- [x] `taxonRank`: technically, `Pieris spec.` should have rank genus?

## MOF extension

- [x] measurementType: `wind force` instead of `wind-force`
- [x] measurementValue (wind force): 4 has a `)`
- [ ] measurementValue: I would write `cloudiness` values as in https://github.com/inbo/soortenmeetnetten-events/issues/2#issuecomment-635392707

**Comment by DimEvil** [comment]
should be ok now!

**Comment by peterdesmet** [comment]
Leaving open to review

**Comment by peterdesmet** [comment]
@DimEvil can you map cloud cover as:

```SQL
WHEN 'heldere hemel (0/8)' THEN 'clear (0/8)'
WHEN 'lichtbewolkt (1 tot 2/8)' THEN 'mostly clear (1/8 - 2/8)'
WHEN 'halfbewolkt (3 tot 5/8)' THEN 'partly cloudy (3/8 - 5/8)'
WHEN 'zwaarbewolkt (6 tot 7/8)' THEN 'mostly cloudy (6/8 - 7/8)'
WHEN 'betrokken (8/8)' THEN 'cloudy (8/8)'
```

With measurementUnit: `okta`.

See this reference: https://www.mentalfloss.com/article/56820/whats-difference-between-mostly-sunny-and-partly-cloudy

**Comment by DimEvil** [comment]
can be closed
