### ISSUE TITLE
Typo in `measurementType` for libellen transects

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#21]
https://ipt.inbo.be/resource?r=meetnetten-libellen-transect-occurrences currently has `lenght transect` (typo) as `measurementType`. In the SQL and whip specs, it is correctly defined as `transect length`:

https://github.com/inbo/meetnetten-occurrences/blob/cb358aea03b2e7c3810e9c93c921634491506745/datasets/8%20meetnetten-libellen-transect-occurrences/specs/dwc_mof.yaml#L9

@DimEvil Did the dataset never get updated with the correct mapping? Is it possible to do so?

**Comment by DimEvil** [comment]
should be ok now
