### ISSUE TITLE
Review of meetnetten-libellen-larvenhuidjes-occurrences data mapping

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#8]
## Event

- [x] datasetName: I suggest `Meetnetten.be - Exuviae counts for dragonflies in Flanders, Belgium`
- [x] samplingProtocol: standardize values
  - `Libellen - Larvenhuidjes` to `exuviae counts`
  - `Libellen - Larvenhuidjes Beekrombout` to `exuviae counts for Gomphus vulgatissimus`

## Occurrence

- [x] lifeStage: `exuviae` not `exuvium` (there is no singular: https://en.wikipedia.org/wiki/Exuviae)

## MOF

- [x] Are these events transects? With a transect length?

**Comment by DimEvil** [comment]
That is what is says in the MoF :)
