### ISSUE TITLE
Change amphibia titles

### ISSUE THREAD

**Issue by peterdesmet** [inbo/meetnetten-occurrences#9]
To be consistent with:

Meetnetten.be - Egg counts for butterflies in Flanders, Belgium
Meetnetten.be - Transects for butterflies in Flanders, Belgium

We should change the titles for:

- [x] Meetnetten.be - Amphibia in fykes in Flanders, Belgium → `Meetnetten.be - Fyke counts for Amphibia in Flanders, Belgium`
- [x] Meetnetten.be - Amphibia larval & metamorph count in Flanders, Belgium → `Meetnetten.be - Larvae and metamorph counts for Amphibia  in Flanders, Belgium`
- [x] Meetnetten.be - Amphibia choir count in Flanders, Belgium → `Meetnetten.be - Choir counts for Amphibia in Flanders, Belgium`

**Comment by peterdesmet** [comment]
@DimEvil debatable, but I think it is better to use "larvae" than "larval" in "larvae count". If agreed, please also update samplingProtocol to `amphibia larvae count`

**Comment by DimEvil** [comment]
all changed
